syntax = "proto3";

package backend.query.v1;

import "backend/common/v1/common.proto";

service FrontendService {
  rpc ListSeasonsOverview(ListSeasonsOverviewRequest) returns (ListSeasonsOverviewResponse);
  rpc ListSeasonEvents(ListSeasonEventsRequest) returns (ListSeasonEventsResponse);
  rpc ListSeasonDrivers(ListSeasonDriversRequest) returns (ListSeasonDriversResponse);
  rpc ListSeasonTeams(ListSeasonTeamsRequest) returns (ListSeasonTeamsResponse);
  rpc ListSeasonCarClasses(ListSeasonCarClassesRequest) returns (ListSeasonCarClassesResponse);

  rpc ListSeasonCarModelVariants(ListSeasonCarModelVariantsRequest) returns (ListSeasonCarModelVariantsResponse);

  rpc ListTrackLayouts(FrontendServiceListTrackLayoutsRequest) returns (FrontendServiceListTrackLayoutsResponse);
}
message ListSeasonsOverviewRequest {
  bool include_inactive = 1;
}
message ListSeasonsOverviewResponse {
  repeated backend.common.v1.Season seasons = 1;
  repeated backend.common.v1.Series series = 2;
  repeated backend.common.v1.Simulation simulations = 3;
}

message ListSeasonEventsRequest {
  uint32 season_id = 1;
}
message EventContainer {
  backend.common.v1.Event event = 1;
  backend.common.v1.Track track = 2;
  backend.common.v1.TrackLayout track_layout = 3;
}
message ListSeasonEventsResponse {
  repeated EventContainer events = 1;
  backend.common.v1.Season season = 2;
  backend.common.v1.Series series = 3;
}

message ListSeasonDriversRequest {
  uint32 season_id = 1;
}

//to be renamed to CarModelVariantContainer?
message CarModelContainer {
  backend.common.v1.CarManufacturer car_manufacturer = 1;
  backend.common.v1.CarModel car_model = 2;
  backend.common.v1.CarModelVariant car_model_variant = 3;
}
message SeasonDriverContainer {
  // the raw data for all season drivers. may contain multiple entries for the same driver
  repeated backend.common.v1.SeasonDriver season_drivers = 1;
  // the driver info for all drivers mentioned in season_drivers.
  repeated backend.common.v1.Driver drivers = 2;
  // the car data for all car models used in season_drivers.
  repeated CarModelContainer car_data = 3;
}
message ListSeasonDriversResponse {
  repeated SeasonDriverContainer items = 1;
}
message ListSeasonTeamsRequest {
  uint32 season_id = 1;
}

message SeasonTeamContainer {
  // the raw data for all season teams. may contain multiple entries for the same team
  repeated backend.common.v1.Team teams = 1;

  // the car data for all car models used in season_teams.
  repeated CarModelContainer car_data = 2;
}
message ListSeasonTeamsResponse {
  repeated SeasonTeamContainer items = 1;
}

message ListSeasonCarClassesRequest {
  uint32 season_id = 1;
}
message ListSeasonCarClassesResponse {
  repeated backend.common.v1.CarClass items = 1;
}

message ListSeasonCarModelVariantsRequest {
  uint32 season_id = 1;
}
message ListSeasonCarModelVariantsResponse {
  repeated backend.common.v1.CarModelVariant items = 1;
}

message FrontendServiceListTrackLayoutsRequest {
  // optional. if set only returns track layouts for the given simulation. if not set, returns all track layouts.
  uint32 simulation_id = 1;
}

message TrackLayoutContainer {
  backend.common.v1.Track track = 1;
  backend.common.v1.TrackLayout track_layout = 2;
}

message FrontendServiceListTrackLayoutsResponse {
  repeated TrackLayoutContainer items = 1;
}
