syntax = "proto3";

package backend.import.v1;

import "backend/common/v1/common.proto";

service ImportService {
  rpc UploadResultsFile(UploadResultsFileRequest) returns (UploadResultsFileResponse);
  rpc ResolveMappings(ResolveMappingsRequest) returns (ResolveMappingsResponse);
  rpc GetPreprocessPreview(GetPreprocessPreviewRequest) returns (GetPreprocessPreviewResponse);
  rpc ApplyResultEdits(ApplyResultEditsRequest) returns (ApplyResultEditsResponse);

  // used to remove data created by the app after an import, for example: result entries, booking entries, penalties, etc.
  // Does not remove manually created data (e.g. manually added penalties) unless include_manual_edits is set to true.
  // If perform_recompute is set to true, will also trigger recomputation of results and standings after cleanup.
  rpc CleanupProcessingData(CleanupProcessingDataRequest) returns (CleanupProcessingDataResponse);

  rpc ComputeBookingEntries(ComputeBookingEntriesRequest) returns (ComputeBookingEntriesResponse);
  rpc AddPenalty(AddPenaltyRequest) returns (AddPenaltyResponse);
  rpc DeletePenalty(DeletePenaltyRequest) returns (DeletePenaltyResponse);
  rpc FinalizeEventProcessing(FinalizeEventProcessingRequest) returns (FinalizeEventProcessingResponse);
}

message UploadResultsFileRequest {
  uint32 race_grid_id = 1;
  backend.common.v1.ImportFormat import_format = 2;
  bytes payload = 3;
}

message UploadResultsFileResponse {
  uint32 race_grid_id = 1;
  string processing_state = 2;
}

message ResolveMappingsRequest {
  uint32 race_grid_id = 1;
}

message ResolveMappingsResponse {
  int32 unresolved_mappings = 1;
}

message GetPreprocessPreviewRequest {
  uint32 race_grid_id = 1;
}

message GetPreprocessPreviewResponse {
  repeated backend.common.v1.ResultEntry rows = 1;
  repeated backend.common.v1.UnresolvedMapping unresolved_mappings = 2;
}

message ApplyResultEditsRequest {
  uint32 race_grid_id = 1;
  repeated backend.common.v1.ResultEntry edited_rows = 2;
}

message ApplyResultEditsResponse {
  int32 updated_rows = 1;
}

message ComputeBookingEntriesRequest {
  uint32 event_id = 1;
}

message ComputeBookingEntriesResponse {
  int32 created_entries = 1;
}

message CleanupProcessingDataRequest {
  CleanupTarget cleanup_target = 1;
  bool include_manual_edits = 2;
  bool perform_recompute = 3;
}

message CleanupTarget {
  oneof target {
    uint32 event_id = 1;
    uint32 race_id = 2;
    uint32 race_grid_id = 3;
  }
}

message CleanupProcessingDataResponse {}

message AddPenaltyRequest {
  PenaltyTarget target = 1;
  int32 penalty_points = 2;
  string reason = 3;
}
message PenaltyTarget {
  oneof scope {
    uint32 event_id = 1;
    uint32 race_id = 2;
    uint32 race_grid_id = 3;
  }
  oneof target {
    uint32 driver_id = 4;
    uint32 team_id = 5;
  }
}

message AddPenaltyResponse {}
message DeletePenaltyRequest {
  uint32 penalty_id = 1;
}
message DeletePenaltyResponse {}

message FinalizeEventProcessingRequest {
  uint32 event_id = 1;
}

message FinalizeEventProcessingResponse {
  string processing_state = 1;
}
